fix docker port
Error: Unable to access http://127.0.0.1:1338.

Resolution: To access http://127.0.0.1:1338, we need to map the port 1338 of our host machine to the port 1337 of the container.